# 사이킷런에서 iris 데이터 다운로드 후 one-hot_encoding까지

In [2]:
from sklearn.datasets import load_iris

iris = load_iris()

In [3]:
X = iris.data
y = iris.target
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [21]:
import tensorflow
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPool2D
from tensorflow.keras.utils import to_categorical

In [5]:
y = to_categorical(y) # keras를 이용한 one-hot_encoding
print(y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Optimizer

In [7]:
# 다중클래스 분류이므로 활성함수를 softmax 함수로 구성
model = Sequential()
model.add(Dense(16, input_dim = 4, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))
model.compile(optimizer='nadam', loss = 'categorical_crossentropy', metrics=['accuracy'])
# 다중 클래스 분류이므로 손실함수를 categorical_crossentropy로 구성

In [8]:
model.fit(X, y, epochs=100, batch_size = 1)

Epoch 1/100
150/150 [==============================] - 2s 2ms/step - loss: 1.0619 - accuracy: 0.5200
Epoch 2/100
150/150 [==============================] - 0s 3ms/step - loss: 0.7070 - accuracy: 0.6800
Epoch 3/100
150/150 [==============================] - 0s 3ms/step - loss: 0.6259 - accuracy: 0.7067
Epoch 4/100
150/150 [==============================] - 0s 2ms/step - loss: 0.5656 - accuracy: 0.7600
Epoch 5/100
150/150 [==============================] - 0s 2ms/step - loss: 0.5184 - accuracy: 0.8067
Epoch 6/100
150/150 [==============================] - 0s 2ms/step - loss: 0.4785 - accuracy: 0.8667
Epoch 7/100
150/150 [==============================] - 0s 2ms/step - loss: 0.4454 - accuracy: 0.9200
Epoch 8/100
150/150 [==============================] - 0s 2ms/step - loss: 0.4147 - accuracy: 0.9467
Epoch 9/100
150/150 [==============================] - 0s 2ms/step - loss: 0.3886 - accuracy: 0.9333
Epoch 10/100
150/150 [==============================] - 0s 2ms/step - loss: 0.3649 - accura

150/150 [==============================] - 0s 2ms/step - loss: 0.0763 - accuracy: 0.9667
Epoch 82/100
150/150 [==============================] - 0s 2ms/step - loss: 0.0727 - accuracy: 0.9733
Epoch 83/100
150/150 [==============================] - 0s 2ms/step - loss: 0.0725 - accuracy: 0.9733
Epoch 84/100
150/150 [==============================] - 0s 2ms/step - loss: 0.0744 - accuracy: 0.9667
Epoch 85/100
150/150 [==============================] - 0s 2ms/step - loss: 0.0713 - accuracy: 0.9600
Epoch 86/100
150/150 [==============================] - 0s 2ms/step - loss: 0.0732 - accuracy: 0.9667
Epoch 87/100
150/150 [==============================] - 0s 2ms/step - loss: 0.0673 - accuracy: 0.9733
Epoch 88/100
150/150 [==============================] - 0s 2ms/step - loss: 0.0713 - accuracy: 0.9733
Epoch 89/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0722 - accuracy: 0.9800
Epoch 90/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0730 - accuracy: 

In [9]:
import numpy as np
model.predict(np.array([[4.7, 3.2, 1.3, 0.2]]))

array([[9.999461e-01, 5.392303e-05, 5.832342e-17]], dtype=float32)

In [10]:
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 2s 0us/step


In [11]:
X_train.dtype
# 정수형 8비트 이므로 32비트 실수형으로 변환해야됨

dtype('uint8')

In [12]:
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

In [13]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

In [26]:
print(X_train.shape[0])
print(X_test.shape[0])

60000
10000


In [15]:
y_train = to_categorical(y_train, num_classes=10)
y_test = to_categorical(y_test, num_classes=10)

In [16]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [17]:
model = Sequential()

In [ ]:
from tensorflow.keras import Input

In [22]:
model.add(Input(shape=(28, 28, 1)))
model.add(Conv2D(6, kernel_size=(3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         multiple                  0         
_________________________________________________________________
conv2d (Conv2D)              (None, 26, 26, 6)         60        
_________________________________________________________________
flatten (Flatten)            (None, 4056)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                40570     
Total params: 40,630
Trainable params: 40,630
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=128, epochs=15, validation_split=0.2)

Epoch 1/15
375/375 [==============================] - 5s 13ms/step - loss: 0.4105 - accuracy: 0.8908 - val_loss: 0.2145 - val_accuracy: 0.9410
Epoch 2/15
375/375 [==============================] - 4s 10ms/step - loss: 0.1797 - accuracy: 0.9496 - val_loss: 0.1429 - val_accuracy: 0.9622
Epoch 3/15
375/375 [==============================] - 4s 10ms/step - loss: 0.1242 - accuracy: 0.9654 - val_loss: 0.1159 - val_accuracy: 0.9686
Epoch 4/15
375/375 [==============================] - 4s 11ms/step - loss: 0.0979 - accuracy: 0.9728 - val_loss: 0.1007 - val_accuracy: 0.9737
Epoch 5/15
375/375 [==============================] - 4s 10ms/step - loss: 0.0827 - accuracy: 0.9767 - val_loss: 0.0950 - val_accuracy: 0.9749
Epoch 6/15
375/375 [==============================] - 4s 11ms/step - loss: 0.0735 - accuracy: 0.9788 - val_loss: 0.0918 - val_accuracy: 0.9737
Epoch 7/15
375/375 [==============================] - 4s 11ms/step - loss: 0.0654 - accuracy: 0.9811 - val_loss: 0.0883 - val_accuracy: 0.9746

In [30]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss: ', score[0])
print('Test accuracy: ', score[1])

Test loss:  0.07643576711416245
Test accuracy:  0.9776999950408936


풀링을 하는 이유:

파라미터의 수를 줄일 수 있다

풀링 자체가 성능을 좋게 하지 않지만

성능의 손실 없으며 피쳐의 손실없이 압축하는 역할

In [32]:
model = Sequential()

model.add(Input(shape=(28, 28, 1)))
model.add(Conv2D(6, kernel_size=(3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 26, 26, 6)         60        
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 13, 13, 6)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1014)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                10150     
Total params: 10,210
Trainable params: 10,210
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=128, epochs=15, validation_split=0.2)

Epoch 1/15
375/375 [==============================] - 6s 15ms/step - loss: 0.6227 - accuracy: 0.8434 - val_loss: 0.2601 - val_accuracy: 0.9263
Epoch 2/15
375/375 [==============================] - 5s 13ms/step - loss: 0.2290 - accuracy: 0.9338 - val_loss: 0.1836 - val_accuracy: 0.9498
Epoch 3/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1688 - accuracy: 0.9524 - val_loss: 0.1539 - val_accuracy: 0.9586
Epoch 4/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1387 - accuracy: 0.9607 - val_loss: 0.1321 - val_accuracy: 0.9633
Epoch 5/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1203 - accuracy: 0.9659 - val_loss: 0.1197 - val_accuracy: 0.9673
Epoch 6/15
375/375 [==============================] - 5s 15ms/step - loss: 0.1078 - accuracy: 0.9694 - val_loss: 0.1192 - val_accuracy: 0.9672
Epoch 7/15
375/375 [==============================] - 5s 14ms/step - loss: 0.0997 - accuracy: 0.9713 - val_loss: 0.1053 - val_accuracy: 0.9712

In [34]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss: ', score[0])
print('Test accuracy: ', score[1])

Test loss:  0.08035455644130707
Test accuracy:  0.973800003528595


In [35]:
model = Sequential()

model.add(Input(shape=(28, 28, 1)))
model.add(Conv2D(6, kernel_size=(3, 3), activation='relu'))
model.add(MaxPool2D(pool_size=(3, 3)))
model.add(Flatten())
model.add(Dense(10, activation='softmax'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 26, 26, 6)         60        
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 8, 8, 6)           0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 384)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                3850      
Total params: 3,910
Trainable params: 3,910
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=128, epochs=15, validation_split=0.2)

Epoch 1/15
375/375 [==============================] - 6s 14ms/step - loss: 0.8235 - accuracy: 0.7884 - val_loss: 0.2960 - val_accuracy: 0.9213
Epoch 2/15
375/375 [==============================] - 5s 14ms/step - loss: 0.2569 - accuracy: 0.9268 - val_loss: 0.2018 - val_accuracy: 0.9443
Epoch 3/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1915 - accuracy: 0.9448 - val_loss: 0.1644 - val_accuracy: 0.9533
Epoch 4/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1593 - accuracy: 0.9544 - val_loss: 0.1461 - val_accuracy: 0.9586
Epoch 5/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1397 - accuracy: 0.9598 - val_loss: 0.1277 - val_accuracy: 0.9643
Epoch 6/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1256 - accuracy: 0.9639 - val_loss: 0.1219 - val_accuracy: 0.9653
Epoch 7/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1151 - accuracy: 0.9668 - val_loss: 0.1114 - val_accuracy: 0.9682

In [37]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss: ', score[0])
print('Test accuracy: ', score[1])

Test loss:  0.0782584398984909
Test accuracy:  0.9751999974250793


cnn

In [52]:
model1 = Sequential()
model1.add(Input(shape =(28, 28, 1)))
model1.add(Conv2D(6, kernel_size=(3, 3), activation='relu'))
model1.add(MaxPool2D(pool_size=(3,3)))
model1.add(Flatten())
model1.add(Dense(10,activation ='softmax'))
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model1.fit(X_train, y_train, batch_size=128, epochs=15, validation_split=0.2)


model2 = Sequential()
model2.add(Input(shape =(28, 28, 1)))
model2.add(Conv2D(6, kernel_size=(3, 3), activation='relu'))
model2.add(MaxPool2D(pool_size=(3,3)))
model2.add(Flatten())
model2.add(Dense(10,activation ='softmax'))
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model2.fit(X_train, y_train, batch_size=128, epochs=15, validation_split=0.2)


model3 = Sequential()
model3.add(Input(shape =(28, 28, 1)))
model3.add(Conv2D(6, kernel_size=(3, 3), activation='relu'))
model3.add(MaxPool2D(pool_size=(3,3)))
model3.add(Flatten())
model3.add(Dense(10,activation ='softmax'))
model3.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model3.fit(X_train, y_train, batch_size=128, epochs=15, validation_split=0.2)

Epoch 1/15
375/375 [==============================] - 5s 13ms/step - loss: 0.7562 - accuracy: 0.7873 - val_loss: 0.3616 - val_accuracy: 0.8947
Epoch 2/15
375/375 [==============================] - 5s 13ms/step - loss: 0.3422 - accuracy: 0.9009 - val_loss: 0.2933 - val_accuracy: 0.9151
Epoch 3/15
375/375 [==============================] - 5s 12ms/step - loss: 0.2858 - accuracy: 0.9167 - val_loss: 0.2499 - val_accuracy: 0.9309
Epoch 4/15
375/375 [==============================] - 5s 13ms/step - loss: 0.2453 - accuracy: 0.9281 - val_loss: 0.2198 - val_accuracy: 0.9376
Epoch 5/15
375/375 [==============================] - 5s 13ms/step - loss: 0.2161 - accuracy: 0.9365 - val_loss: 0.1995 - val_accuracy: 0.9427
Epoch 6/15
375/375 [==============================] - 5s 15ms/step - loss: 0.1927 - accuracy: 0.9438 - val_loss: 0.1779 - val_accuracy: 0.9509
Epoch 7/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1746 - accuracy: 0.9488 - val_loss: 0.1587 - val_accuracy: 0.9562

In [51]:
for i in range(100):
    X_test_re = np.expand_dims(X_test[i], axis=0)
    ensemble_1 = model1.predict(x_test[i])
    ensemble_2 = model2.predict(x_test[i])
    ensemble_3 = model3.predict(x_test[i])
    print('ensemble_1: ', ensemble_1)
    print('ensemble_2: ', ensemble_2)
    print('ensemble_3: ', ensemble_3)

NameError: name 'model1' is not defined

In [39]:
from tensorflow.keras.applications import VGG16

In [40]:
conv_base = VGG16(weights='imagenet', include_top=False, input_shape=(150, 150, 3))  # VGG16 이상한 분야에서 많이 쓰임()

58892288/58889256 [==============================] - 5s 0us/step


In [41]:
conv_base.summary()
# maxpooling에서 끝났다

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 150, 150, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 150, 150, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 150, 150, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 75, 75, 64)        0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 75, 75, 128)       73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 75, 75, 128)       147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 37, 37, 128)       0     

In [42]:
model = Sequential()
model.add(conv_base)
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [43]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Functional)           (None, 4, 4, 512)         14714688  
_________________________________________________________________
flatten_3 (Flatten)          (None, 8192)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 256)               2097408   
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 257       
Total params: 16,812,353
Trainable params: 16,812,353
Non-trainable params: 0
_________________________________________________________________


In [47]:
len(model.trainable_weights)

30

In [48]:
conv_base.trainable = False   # 학습이 안 되게 바꿈
# 플래튼 거기까지만 보고 그것만 왔다갔다 하게 됨
# 오래 걸리지 않게 된다

In [49]:
len(model.trainable_weights)
# 파라미터가 4개라는게 아니라
# 구역이 할당된게 4개로 바뀌었다는......??


4

In [54]:
from tensorflow.keras.applications import ResNet101

In [55]:
conv_base = ResNet101(weights='imagenet', include_top = False, input_shape=(150, 150, 3))

171450368/171446536 [==============================] - 15s 0us/step


In [56]:
conv_base.summary()

Model: "resnet101"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_10 (InputLayer)           [(None, 150, 150, 3) 0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 156, 156, 3)  0           input_10[0][0]                   
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, 75, 75, 64)   9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, 75, 75, 64)   256         conv1_conv[0][0]                 
__________________________________________________________________________________________

In [57]:
model = Sequential()
model.add(conv_base)
model.add(Flatten())
model.add(Dense(256, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [58]:
conv_base.summary()

Model: "resnet101"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_10 (InputLayer)           [(None, 150, 150, 3) 0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 156, 156, 3)  0           input_10[0][0]                   
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, 75, 75, 64)   9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, 75, 75, 64)   256         conv1_conv[0][0]                 
__________________________________________________________________________________________

In [ ]:
갈거야? 쩝,,,,