# 데이터 구조의 이해 (1) - 차원과 배열-1

작성자 - 고우주 | kubwa

In [1]:
# 라이브러리를 임포트합니다. 
import numpy as np

### 2- 1D 배열

In [2]:
# 하나의 행으로 벡터를 만듭니다.
vector_row = np.array([1, 2, 3])

In [3]:
vector_row

array([1, 2, 3])

In [5]:
# 하나의 열로 벡터를 만듭니다.
vector_column = np.array([[1],
                       [2],
                      [3]])

In [6]:
vector_column

array([[1],
       [2],
       [3]])

In [7]:
# 넘파이 배열의 클래스를 출력합니다.
print(type(vector_row))

<class 'numpy.ndarray'>


### 3- 2D 배열

In [8]:
matrix = np.array([[1, 2],
                  [1, 2],
                  [1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [10]:
matrix.shape

(3, 2)

In [11]:
matrix_object = np.mat([[1, 2],
                       [1, 2],
                       [1, 2]])
matrix_object

matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [12]:
matrix_object.shape

(3, 2)

In [14]:
# 영행렬
zero_matrix = np.zeros((3, 2))
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
# 일행렬
one_matrix = np.ones((3, 2))
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 4- 배열 정보 확인

In [21]:
# 행렬을 만듭니다.
matrix = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
# 행렬의 크기를 확인합니다.
matrix.shape

(3, 4)

In [22]:
# 행렬의 원소 개수를 확인합니다 (행 * 열).
matrix.size

12

In [23]:
# 차원 수를 확인합니다.
matrix.ndim

2

In [24]:
# 원소의 데이터 타입을 확인합니다.
print(matrix.dtype)

int32


In [25]:
# 모든 원소에 100을 더합니다.
matrix + 100

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

### 5- 배열 크기 변경

In [27]:
# 라이브러리를 임포트합니다.
import numpy as np

# 4x3 행렬을 만듭니다.
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

# 2x6 행렬로 크기를 바꿉니다.
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
matrix.size

12

In [36]:
# -1은 무슨 뜻이지?
# 아래 두개와 괄호 갯수가 다름
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [37]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
# matrix를 flatten 해서 반환 = 벡터 반환?
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])